---
title: "Introduction to Visualization"
author: "Terrel Shumway"
date: "Thursday, April 16, 2015"
output: html_document
---

This document follows the first lecture series of unit 7.

```{r}
library(ggplot2)

baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"

getdata = function(local){
  if(!file.exists(local)){
    library(downloader)
    remote = paste0(baseurl,local)
    download(remote,local)
  }
  read.csv(local,stringsAsFactors=FALSE)
}
who = getdata("WHO.csv")


```

You can also embed plots, for example:

```{r, echo=FALSE}
plot(who$GNI, who$FertilityRate)

sp = ggplot(who,aes(x=GNI,y=FertilityRate,color=Region))
sp + geom_point()
#sp + geom_line() # not a good visualization for this data set
plot1 = sp + geom_point(colour = "blue", size = 2, shape = 17) + ggtitle("Fertility Rate vs. Gross National Income")
print(plot1)
plot2 = ggplot(who,aes(x=GNI,y=LiteracyRate))
plot2 = plot2 + geom_point() + ggtitle("Literacy Rate vs. Gross National Income")
print(plot2)
```

