---
title: "Document Clustering with Daily KOS"
author: "Terrel Shumway"
date: "Thursday, April 16, 2015"
output: html_document
---

This document presents answers to the questions from part one one of unit six "Document Clustering with Daily KOS".

Load the data.
```{r}
baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"

getdata = function(local){
  if(!file.exists(local)){
    library(downloader)
    remote = paste0(baseurl,local)
    download(remote,local)
  }
  read.csv(local,stringsAsFactors=FALSE)
}
data = getdata("dailykos.csv")
```

## Hierarchical Clustering

problems 1.2,1.3

```{r}
storage = "koscluster.RData.xz"
if(file.exists(storage)){
  load(storage)  
}else{
  distances = dist(data,method="euclidean")  
  cluster = hclust(distances,method="ward.D")
  save(distances,cluster,file=storage,compress="xz")
}

plot(cluster)
```

problem 1.4:
```{r}
k=7
groups = cutree(cluster,k)
table(groups)
```
problem 1.5,1.6
```{r}
lapply(1:k,function(g){head(sort(colMeans(data[groups==g,]),decreasing=TRUE))})
```

## K-means Clustering

```{r}
set.seed(1000)
kluster = kmeans(data,k)
str(kluster)
```

problem 2.1
```{r}
kluster$size[3]
which.max(kluster$size)
which.min(kluster$size)
```

problem 2.2
```{r}
kmc=kluster$centers
lapply(1:k,function(g){head(sort(kmc[g,],decreasing=TRUE))})
```

## Comparing
```{r}
table(groups,kluster$cluster)
```

