---
title: "Unit6 Recitation"
author: "Terrel Shumway"
date: "04/15/2015"
output: html_document
---


```{r}
baseurl = "https://courses.edx.org/c4x/MITx/15.071x_2/asset/"

load = function(local){
  if(!file.exists(local)){
    library(downloader)
    remote = paste0(baseurl,local)
    download(remote,local)
  }
  as.matrix(read.csv(local,header=FALSE))
}
fmatrix = load("flower.csv")
fvector = as.vector(fmatrix)
distances = dist(fvector,method="euclidean")

clusterIntensity = hclust(distances,method="ward.D")

plot(clusterIntensity)
rect.hclust(clusterIntensity, k = 3, border = "red")
flowerClusters = cutree(clusterIntensity, k = 3)


# Plot the image and the clusters
dim(flowerClusters) = c(50,50)
image(flowerClusters, axes = FALSE)

# Original image
image(fmatrix,axes=FALSE,col=grey(seq(0,1,length=256)))

```

```{r}
hmatrix = load("healthy.csv")
hvector = as.vector(hmatrix)
image(hmatrix,axes=FALSE,col=grey(seq(0,1,length=256)))

k = 5
set.seed(1)
KMC = kmeans(hvector,centers=k,iter.max=1000)

hclusters = KMC$cluster
KMC$centers[2]
dim(hclusters) = dim(hmatrix)
image(hclusters,axes=FALSE,col=rainbow(k))

```

```{r}
tmatrix = load("tumor.csv")
tvector = as.vector(tmatrix)
image(tmatrix,axes=FALSE,col=grey(seq(0,1,length=256)))

k = 5
set.seed(1)
KMC = kmeans(tvector,centers=k,iter.max=1000)

tclusters = KMC$cluster
KMC$centers[2]
dim(tclusters) = dim(tmatrix)
image(tclusters,axes=FALSE,col=rainbow(k))

```
