---
title: "D2Hawkeye Claims Modeling"
author: "Terrel Shumway"
date: "04/02/2015"
output: html_document
---

First, we download and read the file `ClaimsData.csv`...

```{r}


claims = read.csv("ClaimsData.csv")
str(claims)

```

split the data into Train and Test sets...

```{r}
#install.packages("caTools")
library(caTools)
set.seed(88)
spl = sample.split(claims$bucket2009,SplitRatio=0.6)
Train = subset(claims,spl)
Test = subset(claims,!spl)

sapply(Train[c("age","diabetes")],mean)

e = function( outcome,prediction){
  conf = table(outcome,prediction)
  n = nrow(outcome)
  accuracy = (conf[1,1]+conf[2,2]+conf[3,3]+conf[4,4]+conf[5,5])/n
  PenaltyMatrix = matrix(c(0,1,2,3,4,
                         2,0,1,2,3,
                         4,2,0,1,2,
                         6,4,2,0,1,
                         8,6,4,2,0),
                       byrow=T,nrow=5)

  penalty = sum(as.matrix(conf)*PenaltyMatrix)/n
  print(accuracy)
  print(penalty)
  c(accuracy=accuracy,penalty=penalty)
}

e(Test$bucket2009,Test$bucket2008)

```

## CART

All of our models are going to use the same independent variables. lets set this once.
```{r}
stformula = bucket2009 ~ age + arthritis + alzheimers + 
    cancer + copd + depression + diabetes + heart.failure +
    ihd + kidney + osteoporosis + stroke +
    bucket2008 + reimbursement2008 

library(rpart)
library(rpart.plot)
Tree = rpart( stformula, data=Train, method="class",cp=0.00005,parms=list(loss=PenaltyMatrix))
#prp(Tree)
p1 = predict(Tree,newdata=Test,type="class")
conf=table(Test$bucket2009,p1)
conf
```

